print("#------------------------------------------#")
print("Tugas 1 SISOP Kelas-B")
print("------------------------------------------")
print("Nama : Chelsea Ayu Adhigiadany")
print("NPM  : 21083010028")
print("------------------------------------------")
print("Notes :")
print("------------------------------------------")
print("Halo Dunia!")
print("Ini adalah script Bash pertamaku di Linux!")
print("#------------------------------------------#")
